### ISSUE TITLE
Error with Jquery 2.0.3

### ISSUE THREAD

**Issue by denniedegroot** [arschmitz/jquery-mobile-datepicker-wrapper#1]
I am getting the following error with the Jquery 2.0.3 library:

``` javascript
[Error] TypeError: 'undefined' is not an object (evaluating '$(object.settings.altField).data("mobileDate")._addMobileStyle')
    (anonymous function) (jquery.mobile.datepicker.js, line 35)
```

Also I cannot seem to get the method calling working. The readme says: $(element).date("method"); but what is the element called? I tried the ID of the input field but thats not working.

**Comment by kartavtcev** [comment]
Hello, I had the same issue today.
Just to illustrate I've created a fiddle, http://jsfiddle.net/r43eX/
Code in js and css fiddle is from example http://jsbin.com/uzaret/938/edit
fiddle is based on jQ 1.9.1
then change jQ to 2.0.x and see that styling stopped working

Hopefully it'll help you here.

**Comment by denniedegroot** [comment]
Commit 83e9705 fixed this issue :)
