### ISSUE TITLE
jquery 2.1 doesn't work with the initial display of the calendar

### ISSUE THREAD

**Issue by bthorington** [arschmitz/jquery-mobile-datepicker-wrapper#17]
If you use jquery 2.1 the initial calendar shows with the jquery ui css (or if not included no css)  once you click on the next/prev month the css is corrected.

here is example
http://jsbin.com/nutevujo/1/edit

**Comment by arschmitz** [comment]
That example is not linking to this repo but instead someone elses fork of it

**Comment by bthorington** [comment]
Sorry about that.. same problem with your repo

http://jsbin.com/nutevujo/5/edit

**Comment by indrimuska** [comment]
The problem is in the beforeShow() callback:
`Uncaught TypeError: Cannot call method 'addMobileStyle' of undefined`

This is a well-known issue and it fixes with #11 or #13: change the call to `.data("mobileDate").addMobileStyle();` to  `.date( "addMobileStyle" );` on line 60.

**Comment by indrimuska** [comment]
This issue is fixes with #19.
