### ISSUE TITLE
Manually typing a date is broken

### ISSUE THREAD

**Issue by codefactor** [arschmitz/jquery-mobile-datepicker-wrapper#2]
![date_picker_issue](https://f.cloud.github.com/assets/730310/1884373/19269f7e-799e-11e3-83e2-0f152690c89e.png)
Manually typing a date into the datepicker is completely broken in all browsers. The version I tested with was jquerymobile 1.4.0.

I found the demo useful and copied the usage on to my own site, and during testing I found this issue. I discovered it also is present in the jquerymobile demo site.

Steps To Reproduce:
1. Open browser of choice
2. Go to: http://demos.jquerymobile.com/1.4.0/datepicker/
3. Focus into any date picker and try typing in "01/01/2014"

Expected Behavior:
You should be able to type in the entire date without interruptions.

Actual Behavior:
After typing the "2" in "2014" the widget tries selecting "2002", then you end up with a date like "01/01/2002014" - Using backspace is no use, it keeps trying to select the date for you.

Also there is some weird behavior causing the background on the calendar to disappear.

**Comment by arschmitz** [comment]
Thank you for reporting this ill look into it.

**Comment by Goats-R-Us** [comment]
Keep up the good work. Desperate for this plus a time picker that is kept current and simple.
Using jQueryUI as the base is brilliant.
Note: forward / backward arrows are a tad off when using ...body class="ui-mini"...

![capture](https://f.cloud.github.com/assets/1842295/1894470/93fd620c-7aeb-11e3-8c7d-426199a930ab.PNG)

**Comment by codefactor** [comment]
Not sure if you're aware - but this page:
http://demos.jquerymobile.com/1.4.0/datepicker/
Is completely broken.

It appears it is expecting: http://view.jqueryui.com/master/ui/jquery.ui.datepicker.js
When in fact the file is: http://view.jqueryui.com/master/ui/datepicker.js
This is just a guess though.
