### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by spencebs** [arschmitz/jquery-mobile-datepicker-wrapper#20]
i moved your root folder to my Dropbox and opened index.html in both Chrome and Firefox on my Note 3 and neither show the calendar. they both look identical though with the input boxes, header and footer. the input box selection css seems to be working. i have js enabled on both browsers and pop up blocker off. 

Thanks!

**Comment by indrimuska** [comment]
Dropbox uses a secure connection trough the HTTPS protocol, but the file you've include in your page use the normal HTTP protocol (if you open the console you can see the requests are blocked).

There are two ways to fix your problem:
- In your browser, change the url of your page and use an **http** (not _https_) connection protocol:
  - `http://dl.dropboxusercontent.com/u/.../datepicker/index.html` 
- In the file index.html, change the url of your scripts removing the protocol before the path:
  - `<link rel="stylesheet"  href="//code.jquery.com/mobile/git/jquery.mobile-git.css" />`
  - `<script src="//code.jquery.com/jquery-1.9.1.js"></script>`
  - `<script src="//code.jquery.com/mobile/git/jquery.mobile-git.js"></script>`

**Comment by spencebs** [comment]
good call indrimuska. thanks for the quick response!

**Comment by indrimuska** [comment]
You're welcome! :+1:

**Comment by spencebs** [comment]
just tested, it does work locally :)

**Comment by spencebs** [comment]
on a side note, I made the input field readonly <input readonly="readonly" ... > 
this disabled the soft keyboard from popping up.

**Comment by arschmitz** [comment]
@indrimuska thanks for jumping in here and taking care of this im going to close since this is not a bug with the widget
