### ISSUE TITLE
datepicker highlight today's date

### ISSUE THREAD

**Issue by spencebs** [arschmitz/jquery-mobile-datepicker-wrapper#21]
sorry i posted last time in the bug section... but i have another question.
how do i get the datepicker to pop up with today's date highlighted?

thanks!

**Comment by arschmitz** [comment]
this is a bug in the popup datepicker i will look into this

**Comment by spencebs** [comment]
posting in the wrong section again. sorry!

**Comment by arschmitz** [comment]
no this is the right place this is the issue tracker

**Comment by indrimuska** [comment]
I think there are two ways to highlight the current day:
1. If you want to set a personal style to the cell, implement the `.ui-datepicker-today` class for the like [this demo](http://jsbin.com/indrimuska/48/edit)
2. If you like the style of the button up already included in jquery mobile, update the `addMobileStyle` method on line 130 like from this:
   `.find(".ui-datepicker-calendar a.ui-state-highlight")
   .addClass("ui-btn-up-"+this.options.theme).end()
   .find(".ui-state-disabled").css("opacity","1");`
   to that:
   `.find(".ui-datepicker-calendar a.ui-state-highlight")
   .addClass("ui-btn-active").end()
   .find(".ui-state-disabled").css("opacity","1");`

**Comment by arschmitz** [comment]
@indrimuska thanks for the work around however we i need to figure out why this is workin on the inline calendar and not on popup

**Comment by indrimuska** [comment]
Oh okay, I've just seen the problem.
Taking a look to the calendar, I see that the inline version add the class `ui-state-active` in the current day link, so that the wrapper can add his own style `ui-btn-active`, but the popup one doesn't.
I think it's a bug in the UI datepicker.

**Comment by arschmitz** [comment]
@indrimuska this works in the ui datepicker http://jqueryui.com/datepicker/

**Comment by indrimuska** [comment]
No it's not. UI datepicker implements his own style (yellow background) for class `.ui-state-highlight` as you can see in the [source code](http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css) on line 872 (search for ".ui-state-highlight").
I'm referring to this demo: http://jqueryui.com/resources/demos/datepicker/default.html.

If you take a look at the inline version (http://jqueryui.com/resources/demos/datepicker/inline.html) the link of the today cell has an extra class `.ui-state-active` that the popup version doesn't have.

If you want to add the mobile style `.ui-btn-active` for the current day you have to change the source of the wrapper on line 130 as I suggested before in the point 2, or better is to change like this:

``` diff
-   .addClass("ui-btn-up-"+this.options.theme)
+   .addClass("ui-btn-up-"+this.options.theme+" ui-btn-active")
```

In this case line 129 is (maybe) not necessary.

**Comment by arschmitz** [comment]
this is fixed in new version closing
