### ISSUE TITLE
How can I localize, translate, dateFormat it?

### ISSUE THREAD

**Issue by prolic** [arschmitz/jquery-mobile-datepicker-wrapper#41]
Can you provide a short example? Thanks

**Comment by indrimuska** [comment]
Look at the ui-datepicker guide
http://api.jqueryui.com/datepicker/

**Comment by prolic** [comment]
I know that url, I wouldn't ask without checking that.

**Comment by indrimuska** [comment]
It's all written in this guide, look at the `$.datepicker.regional`.
One way is doing like that http://jsbin.com/indrimuska/111/edit

**Comment by prolic** [comment]
Thanks a lot. I did all that. The only difference was, that I added

```
data-role="date"
```

leading to a default datepicker shown and whatver settings I made were ignored. Removed that attribute and works great, thanks a lot for your help! ;-)

**Comment by indrimuska** [comment]
Note that this attribute is used for auto-initialization of the datepicker. The way to set default settings for all your date-inputs is very similar to the example I posted.

Maybe you prefer this solution http://jsbin.com/indrimuska/115/edit

**Comment by prolic** [comment]
Many thanks for your assistance! ;)

**Comment by indrimuska** [comment]
You're welcome! :+1:
